### ISSUE TITLE
 Формулировка и обработка запросов сервера

### ISSUE THREAD

**Issue by JoWalker** [JoWalker/QueueAssist#3]

**Comment by KilSys** [comment]
Произведено тестирование.
Обнаружен баг: приложение загружается некорректно(не появляются элементы управления).

**Comment by JoWalker** [comment]
Ошибка исправлена, причина: неправильно прописанный адрес сервера

**Comment by KilSys** [comment]
Произведено тестирование.
Предыдущий баг исправлен.
Обнаружен баг: невозможно записаться в очередь.

**Comment by JoWalker** [comment]
Ошибка исправлена, причина: некорректно работающая функция  записи через API

**Comment by MorellaRavens** [comment]
Исправлены все ошибки, необходимый функционал реализован и многократно протестирован.
